/* CCCWA Site Content — generated by Admin CMS. Edit via admin/index.html */
window.CCCWA_DATA = {
  news: [
    {
      id: "immigration-assets",
      category_en: "Announcement", category_zh: "公告",
      title_en: "CCCWA COVID-19 Weekly Star — Immigration Asset Disposal",
      title_zh: "CCCWA抗击疫情·每周一星 — 移民资产处置问题",
      date_en: "August 24, 2020", date_zh: "2020年8月24日",
      excerpt_en: "Attorney Cai discusses immigration asset management challenges for Chinese families settling in the US, including remote notarization, inheritance, real estate disposal, and cross-border fund transfers during the pandemic.",
      excerpt_zh: "蔡律师讨论华裔家庭在海外安家落户过程中的资产管理挑战，包括远程公证、继承、房产处置和跨境汇款。",
      image: "images/news-1.png",
      article_page: "article-immigration-assets.html",
      featured: true
    },
    {
      id: "covid-community",
      category_en: "Community", category_zh: "社区",
      title_en: "CCCWA Foundation Unites Community Against COVID-19",
      title_zh: "CCCWA一心抗疫，凝聚社区力量",
      date_en: "August 20, 2020", date_zh: "2020年8月20日",
      excerpt_en: "CCCWA Foundation coordinated with local businesses and volunteers across Greater Seattle to support communities affected by COVID-19.",
      excerpt_zh: "CCCWA资助与西雅图地区各个企业和志愿者协调配合，支持受COVID-19影响的社区。",
      image: "images/news-2.png",
      article_page: "article-covid-community.html",
      featured: true
    },
    {
      id: "new-year-2018",
      category_en: "Event", category_zh: "活动",
      title_en: "2018 Chinese New Year Gala Highlights",
      title_zh: "2018年华山州中国总商会春节晚室活动回顾",
      date_en: "2018", date_zh: "2018年",
      excerpt_en: "Hundreds of members and guests gathered to celebrate the Chinese New Year with performances, a gala banquet, and award presentations.",
      excerpt_zh: "数百位会员和宾客欢聚一堂，共贺小灰年，凱举文艺表演、晚室大餐和颁奖典礼。",
      image: "images/news-butterfly.jpg",
      article_page: "article-new-year-2018.html",
      featured: true
    },
    {
      id: "dou-lao-fang",
      category_en: "Community", category_zh: "社区",
      title_en: "Dou Lao Fang Restaurant: One Pot, One World",
      title_zh: "抗击疫情·爱心餐厅系列：豆捶坊——一锅一世界",
      date_en: "2020", date_zh: "2020年",
      excerpt_en: "Feature on Dou Lao Fang restaurant joining CCCWA’s COVID charity meal campaign — supporting the community one meal at a time.",
      excerpt_zh: "豆捶坊餐厅加入CCCWA爱心午餐活动，用一锅汤底迭出爱心，支汇社区。",
      image: "images/news-3.jpg",
      article_page: "article-dou-lao-fang.html",
      featured: true
    },
    {
      id: "meal-drive",
      category_en: "Announcement", category_zh: "公告",
      title_en: "CCCWA COVID Charity Meal Drive — Latest Update",
      title_zh: "CCCWA抗击疫情爱心午餐募捐活动最新动态",
      date_en: "2020", date_zh: "2020年",
      excerpt_en: "Latest update on CCCWA’s charity meal fundraising effort, supporting local restaurants and vulnerable residents affected by COVID-19.",
      excerpt_zh: "最新动态：CCCWA爱心啄募活动，支持受疫情影响的当地餐厅和弱势居民。",
      image: "images/news-4.jpg",
      article_page: "article-meal-drive.html",
      featured: true
    },
    {
      id: "hou-bin",
      category_en: "Event", category_zh: "活动",
      title_en: "Paralympic Ambassador Hou Bin Keynote: Promoting the Olympic Spirit",
      title_zh: "2022年北京宬运会形象大使侯斜先生主题演讲：弘扬奥运精神",
      date_en: "July 2018", date_zh: "2018年7月",
      excerpt_en: "CCCWA hosted Paralympic ambassador Hou Bin for a keynote speech on the Olympic spirit and international cooperation.",
      excerpt_zh: "CCCWA主办残奥会形象大使侯斜先生主题演讲，分享奥运精神与国际合作理念。",
      image: "",
      article_page: "article-hou-bin.html",
      featured: true
    },
    {
      id: "trade-forum-2017",
      category_en: "Community", category_zh: "社区",
      title_en: "China Province & Washington State Trade and Investment Cooperation Forum",
      title_zh: "中国省与华盛顿州贸易投资合作论坛",
      date_en: "July 26, 2017", date_zh: "2017年7月26日",
      excerpt_en: "CCCWA hosted a major forum connecting Chinese provincial delegations with Washington State business and government representatives.",
      excerpt_zh: "CCCWA主办中美贸易投资合作论坛，搭建中国省级代表团与华盛顿州政商界之间的交流平台。",
      image: "images/news-5.png",
      article_page: "article-trade-forum-2017.html",
      featured: true
    },
    {
      id: "hk-anniversary",
      category_en: "Announcement", category_zh: "公告",
      title_en: "CCCWA Celebrates 20th Anniversary of Hong Kong SAR",
      title_zh: "华盛顿州中国总商会庆祝香港特别行政区成立20周年",
      date_en: "July 2017", date_zh: "2017年7月",
      excerpt_en: "CCCWA held a celebration marking the 20th anniversary of the establishment of the Hong Kong Special Administrative Region.",
      excerpt_zh: "CCCWA举办庆典活动，热烈庆祝香港特别行政区回归祖国20周年。",
      image: "",
      article_page: "article-hk-anniversary.html",
      featured: true
    }
  ],
  events: [
    {
      id: "e1",
      month: "JUL", day: "12",
      title_en: "Annual Business Gala & Awards Dinner",
      title_zh: "年度商业晚室及颁奖典礼",
      location_en: "Westin Seattle Hotel, Seattle",
      location_zh: "西雅图威斯汀酒店",
      time: "6:00 PM – 10:00 PM",
      desc_en: "Join us for our flagship annual dinner celebrating CCCWA members and recognizing outstanding contributions to the Washington business community.",
      desc_zh: "诚邀您出席年度旗舰晚室，共同表彰CCCWA会员中的杰出贡献。",
      register_url: "contact.html"
    },
    {
      id: "e2",
      month: "JUL", day: "24",
      title_en: "US-China Trade Forum 2026",
      title_zh: "2026年中美贸易论坛",
      location_en: "Washington State Convention Center",
      location_zh: "华盛顿州展览中心",
      time: "9:00 AM – 5:00 PM",
      desc_en: "A full-day forum featuring keynote speakers, panel discussions, and networking opportunities focused on bilateral trade opportunities.",
      desc_zh: "全天论坛，包括主题演讲、圆桌讨论和交流合作机会。",
      register_url: "contact.html"
    },
    {
      id: "e3",
      month: "AUG", day: "9",
      title_en: "Member Networking Mixer",
      title_zh: "会员交流活动",
      location_en: "Bellevue, WA",
      location_zh: "华盛顿州贝尔维",
      time: "6:30 PM – 9:00 PM",
      desc_en: "A casual networking event for CCCWA members and prospective members. Light refreshments provided. RSVP required.",
      desc_zh: "为CCCWA会员及潜在会员举办的轻松交流活动，提供轻餐，需提前报名。",
      register_url: "contact.html"
    }
  ]
};
